#Server properties
server:
  port: 9004
#Datasource properties
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  sql:
    init:      enabled: true
    
#Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'
    time-zone: UTC
#JPA properties. Using ddl-auto = create will drop schema every-time.
#Choose the correct property based on development / production role.
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        
        
#JWT properties
app:
  jwt:
    header: 
      name: Authorization
      prefix: Bearer
    secret: "mySecret"
    expiration: 900000
#Token properties
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000
  velocity:
    templates:
      location: /templates/
#Logged out token cache
  cache:
    logoutToken:
      maxSize: 1000

